spring.application.name=HospitalManagementSystem

spring.datasource.name=product
spring.datasource.url=jdbc:mysql://localhost:3306/HMS_copy
spring.datasource.username=root
spring.datasource.password=Aditya@2262

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=9090

server.servlet.context-path=/hms
